server:
  http_listen_port: 9081
  grpc_listen_port: 0
  log_level: info

positions:
  filename: /tmp/positions-local.yaml

clients:
  - url: https://loki.jclee.me/loki/api/v1/push

scrape_configs:
  # Claude Code history logs
  - job_name: claude-code
    static_configs:
      - targets:
          - localhost
        labels:
          job: claude-code
          host: jclee-dev
          environment: development
          service: claude-code
          __path__: /claude-logs/history.jsonl

    pipeline_stages:
      # Parse JSON logs
      - json:
          expressions:
            display: display
            project: project
            timestamp: timestamp

      # Convert timestamp to time
      - timestamp:
          source: timestamp
          format: Unix
          fallback_formats:
            - UnixMs

      # Extract project name from path
      - regex:
          source: project
          expression: '\/([^\/]+)$'

      # Set labels
      - labels:
          display:

      # Output message
      - output:
          source: display

  # Claude Code project logs
  - job_name: claude-projects
    static_configs:
      - targets:
          - localhost
        labels:
          job: claude-code
          host: jclee-dev
          environment: development
          service: claude-projects
          __path__: /claude-logs/projects/**/*.jsonl

    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            role: role
            content: content

      - timestamp:
          source: timestamp
          format: UnixMs

      - labels:
          role:

      - output:
          source: content

  # System logs (optional)
  - job_name: system-logs-local
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          host: jclee-dev
          environment: development
          __path__: /var/log/messages

    pipeline_stages:
      - match:
          selector: '{job="system"}'
          stages:
            - regex:
                expression: '^(?P<time>\S+\s+\d+\s+\d+:\d+:\d+)\s+(?P<hostname>\S+)\s+(?P<process>\S+):\s+(?P<message>.*)$'
            - labels:
                hostname:
                process:
            - output:
                source: message
